ALTER TABLE parametros RENAME TO parametro;
ALTER TABLE contratistas RENAME TO contratista;
ALTER TABLE empleados RENAME TO empleado;
ALTER TABLE parametro_reporte RENAME TO parametros_reporte;
ALTER TABLE procesos_reportes RENAME TO tipo_proceso_reporte;
ALTER TABLE parametros_reporte RENAME COLUMN fk_reporte TO id_reporte;
ALTER TABLE parametros_reporte RENAME COLUMN fk_data TO id_data;
ALTER TABLE parametros_reporte RENAME COLUMN fk_tipo TO id_tipo;
ALTER TABLE reporte RENAME COLUMN fk_proceso TO id_proceso;
ALTER TABLE archivo RENAME COLUMN fk_reporte TO id_reporte;
ALTER TABLE archivo RENAME COLUMN fk_tipo_archivo TO id_tipo_archivo;
ALTER TABLE trabajo RENAME COLUMN FK_estado_trabajo_id TO id_estado_trabajo;
ALTER TABLE trabajo RENAME COLUMN FK_equipos_id TO id_equipos;
ALTER TABLE trabajo RENAME COLUMN FK_areas_trabajo_id TO id_areas_trabajo;
ALTER TABLE trabajo RENAME COLUMN FK_ejecutante_id TO id_ejecutante;
ALTER TABLE trabajo RENAME COLUMN FK_solicitante_id TO id_solicitante;
ALTER TABLE trabajo RENAME COLUMN FK_proyecto_id TO id_proyecto;
ALTER TABLE areas_trabajo RENAME COLUMN FK_autoridades_id TO id_autoridades;
ALTER TABLE trazabilidad_trabajo RENAME COLUMN FK_trabajo_id TO id_trabajo;
ALTER TABLE trazabilidad_trabajo RENAME COLUMN FK_usuario_id TO id_usuario;
ALTER TABLE trazabilidad_trabajo RENAME COLUMN FK_estado_trazabilidad_id TO id_estado_trazabilidad;
ALTER TABLE autoridades RENAME TO autoridad;
ALTER TABLE autoridad RENAME COLUMN FK_tipos_autoridades_id TO id_tipos_autoridades;
ALTER TABLE autoridad RENAME COLUMN FK_usuario_id TO id_usuario;
ALTER TABLE tipos_autoridades RENAME TO tipo_autoridade;
ALTER TABLE tipo_autoridade RENAME TO tipo_autoridad;
ALTER TABLE certificados RENAME TO certificado;
ALTER TABLE certificados_trabajo RENAME COLUMN FK_autoridades_id TO id_autoridad;
ALTER TABLE certificados_trabajo RENAME COLUMN FK_certificados_id TO id_certificado;
ALTER TABLE certificados_trabajo RENAME COLUMN FK_permiso_id TO id_permiso;
ALTER TABLE precauciones_trabajo RENAME COLUMN FK_permiso_id TO id_permiso;
ALTER TABLE precauciones_trabajo RENAME COLUMN FK_precaucion_id TO id_precaucion;
ALTER TABLE precauciones_trabajo RENAME COLUMN FK_autoridades_id TO id_autoridad;
ALTER TABLE areas_afectadas_permiso RENAME COLUMN FK_areas_trabajo_id TO id_areas_trabajo;
ALTER TABLE areas_afectadas_permiso RENAME COLUMN FK_permiso_id TO id_permiso;
ALTER TABLE disciplinas RENAME TO disciplina;
ALTER TABLE controles_trabajo RENAME COLUMN FK_permiso_id TO id_permiso;
ALTER TABLE controles_trabajo RENAME COLUMN FK_control_id TO id_control;
ALTER TABLE riesgos_trabajo RENAME COLUMN FK_riesgo_id TO id_riesgo;
ALTER TABLE riesgos_trabajo RENAME COLUMN FK_permiso_id TO id_permiso;
ALTER TABLE control RENAME COLUMN FK_riesgo_id TO id_riesgo;
ALTER TABLE equipos RENAME TO equipo;
ALTER TABLE formularios RENAME TO formulario;
ALTER TABLE campos_validaciones RENAME TO campos_validacion;
ALTER TABLE empleados_proyectos RENAME TO empleados_proyecto;
